# Generated by Django 3.2 on 2024-11-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('fecha_registro', models.DateTimeField()),
                ('vehiculo_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_Reserva', models.DateTimeField()),
                ('fecha_Reserva', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('administrador_id', models.IntegerField()),
                ('servicio_id', models.IntegerField()),
                ('clientes_id', models.IntegerField()),
                ('clientes_id_vehiculo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=45)),
                ('calificacion', models.CharField(max_length=45)),
                ('fecha_review', models.DateField()),
                ('clientes_id', models.IntegerField()),
                ('clientes_id_vehiculo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45)),
                ('modelo', models.CharField(max_length=45)),
                ('year', models.CharField(max_length=45)),
                ('patente', models.CharField(max_length=5)),
            ],
        ),
    ]
