# Generated by Django 3.2 on 2024-11-09 20:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='fecha_Reserva',
            new_name='fecha_reserva',
        ),
        migrations.RenameField(
            model_name='reservas',
            old_name='hora_Reserva',
            new_name='hora_reserva',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='vehiculo_id',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='administrador_id',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='clientes_id',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='clientes_id_vehiculo',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='servicio_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='clientes_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='clientes_id_vehiculo',
        ),
        migrations.AddField(
            model_name='clientes',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.encargado'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clientes'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.servicios'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clientes'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
