# Generated by Django 3.2 on 2024-11-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20241109_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='correo',
            field=models.EmailField(max_length=45),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha_reserva',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='calificacion',
            field=models.IntegerField(),
        ),
    ]
