# Generated by Django 3.2 on 2024-11-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20241110_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
