# Generated by Django 3.2 on 2024-11-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20241110_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='password',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='password',
        ),
        migrations.AddField(
            model_name='clientes',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encargado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.encargado'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clientes'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.servicios'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clientes'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
    ]
