# Generated by Django 3.2 on 2024-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20241113_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='servicio',
        ),
        migrations.AddField(
            model_name='reservas',
            name='servicios',
            field=models.ManyToManyField(to='app1.Servicios'),
        ),
    ]
