# Generated by Django 3.2 on 2024-11-10 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_auto_20241110_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('telefono', models.CharField(max_length=45, null=True)),
                ('direccion', models.CharField(max_length=45, null=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_reserva', models.DateTimeField(null=True)),
                ('fecha_reserva', models.DateTimeField(null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=45, null=True)),
                ('calificacion', models.IntegerField(null=True)),
                ('fecha_review', models.DateField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('precio', models.IntegerField(null=True)),
                ('duracion', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='vehiculo',
        ),
        migrations.RemoveField(
            model_name='encargado',
            name='user',
        ),
        migrations.AddField(
            model_name='encargado',
            name='correo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='encargado',
            name='nombre',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='encargado',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='telefono',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='modelo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='year',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.AddField(
            model_name='review',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.encargado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.servicio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='vehiculo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.vehiculo'),
        ),
    ]
